#!/usr/bin/env python3
"""
Create a double-clickable Terminal launcher for the chat, on the Desktop.

    python shortcuts/make_launcher.py
    ./mabel desktop                        # same thing

Writes `Mabel.command` to ~/Desktop. Double-clicking it opens a Terminal
window running `./mabel` — the interactive chat. The project path is embedded,
so re-run the command if you move the folder.

macOS only: a .command file is a Terminal convention.
"""

import json
import subprocess
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = Path.home() / "Desktop" / "Mabel.command"
ICON = PROJECT / "assets" / "Mabel.icns"

SCRIPT = r"""#!/usr/bin/env bash
# Inbox triage chat. Generated by: ./mabel desktop
# Re-run that command if you move the project folder.

BOLD=$'\033[1m'
CYAN=$'\033[36m'
GREEN=$'\033[32m'
RESET=$'\033[0m'
BOX_TOP="┌────────────────────────────────────────┐"
BOX_BOT="└────────────────────────────────────────┘"

PROJECT={project}
cd "$PROJECT" 2>/dev/null || {{
  echo "Mail agent not found at $PROJECT."
  read -r -p "Press Return to close."
  exit 1
}}
if [ ! -x ./mabel ]; then
  echo "Mabel is missing here. Run './mabel desktop' from the project folder."
  read -r -p "Press Return to close."
  exit 1
fi

clear
printf '%s%s%s\n' "$CYAN" "$BOX_TOP" "$RESET"
printf '%s│%s       %s📬  Mabel%s       %s│%s\n' \\
       "$CYAN" "$RESET" "$BOLD" "$RESET" "$CYAN" "$RESET"
printf '%s%s%s\n\n' "$CYAN" "$BOX_BOT" "$RESET"
printf '  %sStarting inbox triage...%s\n\n' "$GREEN" "$RESET"
sleep 1
./mabel
echo
printf '\n%s──────────────────────────────────────────%s\n' "$CYAN" "$RESET"
read -r -p "Session ended. Press Return to close this window. "
"""


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(SCRIPT.format(project=json.dumps(str(PROJECT))))
    OUT.chmod(0o755)

    # Set the custom icon on the .command file (macOS only)
    if ICON.exists():
        try:
            subprocess.run(["fileicon", "set", str(OUT), str(ICON)],
                           check=False, capture_output=True)
        except (OSError, subprocess.SubprocessError):
            pass

    print(f"Created {OUT}")
    print("Double-click it on the Desktop to open the chat in Terminal.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
