#!/usr/bin/env python3
"""
Create a double-clickable Terminal launcher for the chat, on the Desktop.

    python shortcuts/make_launcher.py
    ./mabel desktop                        # same thing

Writes `Mabel.command` to ~/Desktop. Double-clicking it opens a Terminal
window running `./mabel` — the interactive chat. The project path is embedded,
so re-run the command if you move the folder.

macOS only: a .command file is a Terminal convention.
"""

import json
import subprocess
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = Path.home() / "Desktop" / "Mabel.command"
ICON = PROJECT / "assets" / "Mabel.icns"

SCRIPT = r"""#!/usr/bin/env bash
# Mabel — inbox triage chat. Generated by: ./mabel desktop
# Re-run that command if you move the project folder.

DIM=$'\033[2m'
RED=$'\033[31m'
RESET=$'\033[0m'

# Name the window and give it room: a chat in the 80x24 default wraps the
# triage badly. Standard xterm sequences, which Terminal.app honours — but
# only sent to a real terminal, since anywhere else they would print as
# literal junk.
if [ -t 1 ]; then
  printf '\033]0;Mabel\007'
  printf '\033[8;44;104t'
fi

PROJECT={project}

fail() {{
  printf '\n  %sMabel could not start%s\n  %s\n\n' "$RED" "$RESET" "$1"
  printf '  Press Return to close. '
  read -r _
  exit 1
}}

cd "$PROJECT" 2>/dev/null || fail "The project folder has moved from $PROJECT."
[ -x ./mabel ] || fail "./mabel is missing. Run './mabel desktop' from the project."

clear
# One quiet line while the venv, mailbox and model come up — that can take
# twenty seconds cold, and a blank window reads as a hang. Deliberately does
# not say "Mabel": the agent prints its own banner the moment it is ready,
# and the name twice in four lines is just noise.
printf '%s  starting…%s' "$DIM" "$RESET"
./mabel
status=$?

printf '\n%s  ────────────────────────────%s\n' "$DIM" "$RESET"
if [ $status -ne 0 ]; then
  printf '%s  Ended with an error (exit %s).%s\n' "$DIM" "$status" "$RESET"
fi
printf '%s  Press Return to close.%s ' "$DIM" "$RESET"
read -r _
"""


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(SCRIPT.format(project=json.dumps(str(PROJECT))))
    OUT.chmod(0o755)

    # Set the custom icon on the .command file (macOS only)
    if ICON.exists():
        try:
            subprocess.run(["fileicon", "set", str(OUT), str(ICON)],
                           check=False, capture_output=True)
        except (OSError, subprocess.SubprocessError):
            pass

    print(f"Created {OUT}")
    print("Double-click it on the Desktop to open the chat in Terminal.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
